const fs = require('fs');

// 1. Fix jobsRoutes.js
let jobsContent = fs.readFileSync('server/api/routes/jobsRoutes.js', 'utf8');
const jobsTarget = `      if (!isAutoJob) {
        // RETRY MANUAL: bangun ulang kandidat dari link tersimpan (youtubeUrl + OEM). TANPA pencarian web.
        const allUrls = [originalYoutubeUrl, ...savedOemUrls].filter(Boolean);
        if (allUrls.length === 0) {
          throw new Error('Job manual tidak memiliki URL sumber tersimpan untuk di-retry. Kirim ulang link video aslinya.');
        }
        targetCandidates = allUrls.map(u => ({ url: u, title: job.productTitle }));`;
const jobsReplacement = `      if (!isAutoJob) {
        // RETRY MANUAL: bangun ulang kandidat dari link tersimpan (youtubeUrl + OEM). TANPA pencarian web.
        const allUrls = [originalYoutubeUrl, ...savedOemUrls].filter(Boolean);
        if (allUrls.length === 0) {
          throw new Error('Job manual tidak memiliki URL sumber tersimpan untuk di-retry. Kirim ulang link video aslinya.');
        }
        targetCandidates = allUrls.map(u => ({ url: u, title: job.productTitle }));
        // [FIX] Force explicitOnly for manual retries
        if (!job.options) job.options = {};
        job.options.explicitOnly = true;`;
if (jobsContent.includes(jobsTarget)) {
  jobsContent = jobsContent.replace(jobsTarget, jobsReplacement);
  fs.writeFileSync('server/api/routes/jobsRoutes.js', jobsContent, 'utf8');
  console.log('Fixed jobsRoutes.js');
} else {
  console.log('Could not find target in jobsRoutes.js');
}

// 2. Fix generateRoutes.js
let genContent = fs.readFileSync('server/api/routes/generateRoutes.js', 'utf8');
const genTarget = `    const stage1Result = await runStage1Pipeline({
      jobId,
      youtubeUrl,
      shopeeLink,
      productTitle,
      productDescription,
      apiKey,
      options,
    });`;
const genReplacement = `    if (!options.isAutoGenerated) {
      options.explicitOnly = true;
    }
    const stage1Result = await runStage1Pipeline({
      jobId,
      youtubeUrl,
      shopeeLink,
      productTitle,
      productDescription,
      apiKey,
      options,
    });`;
if (genContent.includes(genTarget)) {
  genContent = genContent.replace(genTarget, genReplacement);
  fs.writeFileSync('server/api/routes/generateRoutes.js', genContent, 'utf8');
  console.log('Fixed generateRoutes.js');
} else {
  console.log('Could not find target in generateRoutes.js');
}
