const fs = require('fs');
let code = fs.readFileSync('server/worker/stage1Render.js', 'utf8');

// 1. Insert variables before Master Loop
const preLoopStr = '    let candidateResults = [];\n    let hl = null;\n';
const preLoopInsert = preLoopStr + '    const isAutoModeFallback = Boolean(extraJobMeta?.isAutoGenerated);\n    let isBrandDetected = false;\n    let scriptData = null;\n    let rawVoiceScript = null;\n    let autoVoiceoverPath = null;\n    let silentDurationSec = 0;\n    let ttsSucceeded = false;\n    let visionSummary = null;\n';
code = code.replace(preLoopStr, preLoopInsert);

// 2. Wrap body in try-catch
// Find start:
const loopStart = '    while (!finalCompletedJob && masterRetryCount < 3 && !forceManualFallback) {';
const loopStartRepl = loopStart + '\n      try {';
code = code.replace(loopStart, loopStartRepl);

// Find end:
const loopEnd = '    } // Akhir Master Loop';
const loopEndRepl = '      } catch (masterLoopErr) {\n        if (isAutoModeFallback && masterLoopErr.isAiRejection) {\n          console.warn(`[Job ${jobId}] ⚠️ Pipeline tertunda (isAiRejection=true): ${masterLoopErr.message}. Meneruskan ke iterasi Master Loop untuk mencari video lain...`);\n          if (candidateResults) {\n            candidateResults.forEach(c => {\n              if (c.candidate && c.candidate.url) failedCandidateUrls.add(c.candidate.url);\n            });\n            candidateResults = [];\n          }\n          continue;\n        }\n        throw masterLoopErr;\n      }\n    } // Akhir Master Loop';
code = code.replace(loopEnd, loopEndRepl);

// 3. Remove inner declarations
code = code.replace('const isAutoModeFallback = Boolean(extraJobMeta?.isAutoGenerated);', '');
code = code.replace('const visionSummary = summarizeVisionRuns(visionState.runs);', 'visionSummary = summarizeVisionRuns(visionState.runs);');
code = code.replace('let scriptData;', 'scriptData = null;');
code = code.replace('const rawVoiceScript = scriptData.voiceoverScript || scriptData.aiStudioPrompt || \'\';', 'rawVoiceScript = scriptData.voiceoverScript || scriptData.aiStudioPrompt || \'\';');
code = code.replace('const autoVoiceoverPath = path.join(uploadsDir, voiceoverFileName);', 'autoVoiceoverPath = path.join(uploadsDir, voiceoverFileName);');
code = code.replace('const silentDurationSec = (await getMediaDurationSec(silentOutputPath)) || highlight.duration || 20;', 'silentDurationSec = (await getMediaDurationSec(silentOutputPath)) || highlight.duration || 20;');
code = code.replace('let ttsSucceeded = false;', 'ttsSucceeded = false;');
code = code.replace('const isBrandDetected = highlight.hasProductBrand === true ||', 'isBrandDetected = highlight.hasProductBrand === true ||');

fs.writeFileSync('server/worker/stage1Render.js', code, 'utf8');
console.log('Patch applied!');
