// P2 JARING PENGAMAN — Kontrak RETRY MANUAL (regression guard sebelum refactor P6).
// Menegakkan aturan inti: retry job MANUAL wajib memakai URL sumber tersimpan
// (sourcePolicy:'explicit_only') dan TIDAK PERNAH memanggil mesin telusur (nol pencarian web).
// Pipeline & discovery di-mock => tidak ada AI/jaringan/FFmpeg sungguhan yang jalan.
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import http from 'http';

// --- Mock batas terluar (P2.4): hentikan dunia luar (AI, jaringan, FFmpeg, discovery). ---
const runStage1Pipeline = vi.fn(() => Promise.resolve());
const discoverYouTubeCandidatesForProduct = vi.fn(() => Promise.resolve([]));

vi.mock('../worker/pipelineWorker.js', async (importOriginal) => {
  const actual = await importOriginal();
  return { ...actual, runStage1Pipeline: (...args) => runStage1Pipeline(...args) };
});
vi.mock('../services/discoveryService.js', async (importOriginal) => {
  const actual = await importOriginal();
  return { ...actual, discoverYouTubeCandidatesForProduct: (...args) => discoverYouTubeCandidatesForProduct(...args) };
});

// Import SETELAH mock terpasang (hoisting vitest menjamin mock jalan sebelum modul di-load).
const { default: jobsRoutes } = await import('../api/routes/jobsRoutes.js');
const { activeJobs } = await import('../store/jobStore.js');
const express = (await import('express')).default;

let server;
let baseUrl;
beforeEach(async () => {
  runStage1Pipeline.mockClear();
  discoverYouTubeCandidatesForProduct.mockClear();
  const app = express();
  app.use(express.json());
  app.use('/api', jobsRoutes);
  await new Promise((resolve) => {
    server = app.listen(0, () => {
      baseUrl = `http://127.0.0.1:${server.address().port}`;
      resolve();
    });
  });
});
afterEach(async () => {
  if (server) await new Promise((resolve) => server.close(resolve));
});

// Menunggu job async di belakang route selesai (retry merespons 200 lalu menjalankan IIFE).
const flushAsync = (ms = 60) => new Promise((r) => setTimeout(r, ms));

const post = async (path, body) => {
  const res = await fetch(`${baseUrl}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {}),
  });
  return { status: res.status, json: await res.json().catch(() => ({})) };
};

describe('POST /api/jobs/:jobId/retry — kontrak manual vs auto', () => {
  it('job 404 bila jobId tidak dikenal', async () => {
    const { status, json } = await post('/api/jobs/tidak_ada_retry/retry', {});
    expect(status).toBe(404);
    expect(json.error).toMatch(/tidak ditemukan/);
    expect(runStage1Pipeline).not.toHaveBeenCalled();
  });

  it('RETRY MANUAL memakai URL tersimpan + sourcePolicy:explicit_only + TANPA pencarian web', async () => {
    const jobId = 'retry_manual_ok';
    activeJobs.set(jobId, {
      id: jobId,
      productTitle: 'Pisau Serbaguna',
      productCategory: 'gadget_smartphone',
      youtubeUrl: 'https://youtu.be/MANUAL123',
      oemUrls: ['https://shopee.foo/1', '', 'https://shopee.foo/2'],
      singleVideoOnly: false,
      // isAutoGenerated absent => manual
    });

    const { status } = await post(`/api/jobs/${jobId}/retry`, {});
    expect(status).toBe(200);
    await flushAsync();

    // Nol pencarian web: discovery TIDAK boleh dipanggil untuk job manual.
    expect(discoverYouTubeCandidatesForProduct).not.toHaveBeenCalled();

    expect(runStage1Pipeline).toHaveBeenCalledTimes(1);
    const arg = runStage1Pipeline.mock.calls[0][0];
    expect(arg.jobId).toBe(jobId);
    expect(arg.youtubeUrl).toBe('https://youtu.be/MANUAL123');
    expect(arg.requireCleanGeminiPlan).toBe(true);
    expect(arg.options).toMatchObject({
      autoSearchFallback: false,
      sourcePolicy: 'explicit_only',
      singleVideoOnly: false,
      niche: 'gadget_smartphone',
      // ALUR BARU: retry manual niche smartphone ikut set render autojob.
      multiVideoHarvesting: true,
      isVideoFirst: true,
      sceneDuration: 3.3,
      minDuration: 30.0,
    });
    // LOCK manual TETAP: menambah multiVideoHarvesting TIDAK boleh membuka auto-search.
    expect(arg.options.autoSearchFallback).toBe(false);
    expect(arg.options.sourcePolicy).toBe('explicit_only');
    // oemUrls tersaring (string kosong dibuang), urutan & isi terjaga.
    expect(arg.options.oemUrls).toEqual(['https://shopee.foo/1', 'https://shopee.foo/2']);
    activeJobs.delete(jobId);
  });

  it('RETRY MANUAL tanpa youtubeUrl memakai oemUrls[0] sebagai kandidat utama', async () => {
    const jobId = 'retry_manual_oem';
    activeJobs.set(jobId, {
      id: jobId,
      productTitle: 'Wajan Anti Lengket',
      niche: 'kitchen_tools',
      youtubeUrl: '',
      oemUrls: ['https://youtu.be/FROM_OEM'],
    });

    const { status } = await post(`/api/jobs/${jobId}/retry`, {});
    expect(status).toBe(200);
    await flushAsync();

    expect(discoverYouTubeCandidatesForProduct).not.toHaveBeenCalled();
    expect(runStage1Pipeline).toHaveBeenCalledTimes(1);
    const arg = runStage1Pipeline.mock.calls[0][0];
    expect(arg.youtubeUrl).toBe('https://youtu.be/FROM_OEM');
    expect(arg.options.sourcePolicy).toBe('explicit_only');
    expect(arg.options.niche).toBe('kitchen_tools');
    // ALUR BARU: retry manual niche alat dapur ikut set render autojob (tanpa cari web).
    expect(arg.options).toMatchObject({ multiVideoHarvesting: true, isVideoFirst: true, sceneDuration: 3.3, minDuration: 30.0 });
    expect(discoverYouTubeCandidatesForProduct).not.toHaveBeenCalled();
    activeJobs.delete(jobId);
  });

  it('RETRY MANUAL tanpa URL sumber apa pun => gagal (stage error, tanpa pipeline)', async () => {
    const jobId = 'retry_manual_noSource';
    activeJobs.set(jobId, { id: jobId, productTitle: 'Tanpa Sumber', youtubeUrl: '', oemUrls: [] });

    const { status } = await post(`/api/jobs/${jobId}/retry`, {});
    expect(status).toBe(200);
    await flushAsync();

    expect(runStage1Pipeline).not.toHaveBeenCalled();
    expect(discoverYouTubeCandidatesForProduct).not.toHaveBeenCalled();
    const after = activeJobs.get(jobId);
    expect(after.stage).toBe('error');
    expect(after.lastError).toMatch(/tidak memiliki URL sumber tersimpan/);
    activeJobs.delete(jobId);
  });

  it('RETRY AUTO (isAutoGenerated) boleh memanggil discovery & omit sourcePolicy', async () => {
    const jobId = 'retry_auto_ok';
    activeJobs.set(jobId, {
      id: jobId,
      isAutoGenerated: true,
      productTitle: 'HP Murah 2 Jutaan',
      niche: 'gadget_smartphone',
      youtubeUrl: 'https://youtu.be/AUTOOLD',
    });
    discoverYouTubeCandidatesForProduct.mockResolvedValue([{ url: 'https://youtu.be/AUTONEW', title: 'Baru' }]);

    const { status } = await post(`/api/jobs/${jobId}/retry`, { forceNewCandidate: true });
    expect(status).toBe(200);
    await flushAsync();

    expect(discoverYouTubeCandidatesForProduct).toHaveBeenCalledTimes(1);
    expect(runStage1Pipeline).toHaveBeenCalledTimes(1);
    const arg = runStage1Pipeline.mock.calls[0][0];
    // Cabang auto TIDAK mengunci explicit_only.
    expect(arg.options.sourcePolicy).toBeUndefined();
    expect(arg.youtubeUrl).toBe('https://youtu.be/AUTONEW');
    // ALUR BARU: retry auto niche smartphone ikut set render autojob.
    expect(arg.options).toMatchObject({ multiVideoHarvesting: true, isVideoFirst: true, sceneDuration: 3.3, minDuration: 30.0, niche: 'gadget_smartphone' });
    activeJobs.delete(jobId);
  });
});
